PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": "5f65f4f2-fb84-4273-b7be-dc246c980dba",
  "title": "What's new with NestJS and Typescript 8c",
  "tags": ["237d9a53-842d-448d-999b-f1b2eb6eb0c6", "b694f4b5-f842-4731-b598-459a95adf452"]

}