PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": "167abdd2-4886-40bb-b5d7-a4b99dc1d0de",
  "title": "What's new with NestJS and Typescript 5",
  "tags": ["54b5ebe1-805c-48b0-b926-9485873635db"]


}