POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "What's new with NestJS 7",
  "description": "This is the description of my post 7",
  "postType": "post",
  "slug": "new-with-nest-js-7",
  "status": "DRAFT",
  "content": "post-content",
  "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishedOn": "2024-03-16T07:46:32+0000",
  "metaOptions":
    {
       "metaValue": "{ \"sidebarEnabled\": false, \"footerActive\": false }"
    },
  "authorId": "adcc0431-afae-46c2-bc89-4e52cf6f16a9",
  "tags": ["67c92d3c-5a2f-4c3d-8b5e-41d01645ba57", "fe4b645d-fcfc-4ce8-b795-f905ca8ceb82"]
}