POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Smith",
  "username": "johnsmith",
  "email": "johnsmith@gmail.com",
  "password": "Password123#"
}
