POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe 3",
  "username": "johndoe3",
  "email": "john3@doe.com",
  "password": "Password123#"
}
